[_PROJECT]
env=["GTEST_COLOR=1"]
run=""
clean="rm -rf ./build"
build="make -C build -j4"
config="cmake -B build -DSHOGLE_ENABLE_IMGUI=1"
target="osm_client"
target_config="debug"

[osm_client]
run="mangohud --dlsym ./build/osm_client"

[osm_client.configs]
debug=["-DCMAKE_BUILD_TYPE=Debug"]
release=["-DCMAKE_BUILD_TYPE=Release"]
